// Code generated by Fern. DO NOT EDIT.

package statistic_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestStatisticBasicStatsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.BasicStatsRequest{
		EndDate: payabli.String(
			"2025-11-01",
		),
		StartDate: payabli.String(
			"2025-11-30",
		),
	}
	_, invocationErr := client.Statistic.BasicStats(
		context.TODO(),
		int64(1000000),
		"m",
		1,
		"ytd",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatisticBasicStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatisticBasicStatsWithWireMock", "GET", "/Statistic/basic/ytd/m/1/1000000", map[string]string{"endDate": "2025-11-01", "startDate": "2025-11-30"}, 1)
}

func TestStatisticCustomerBasicStatsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.CustomerBasicStatsRequest{}
	_, invocationErr := client.Statistic.CustomerBasicStats(
		context.TODO(),
		998,
		"m",
		"ytd",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatisticCustomerBasicStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatisticCustomerBasicStatsWithWireMock", "GET", "/Statistic/customerbasic/ytd/m/998", nil, 1)
}

func TestStatisticSubStatsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.SubStatsRequest{}
	_, invocationErr := client.Statistic.SubStats(
		context.TODO(),
		int64(1000000),
		"30",
		1,
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatisticSubStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatisticSubStatsWithWireMock", "GET", "/Statistic/subscriptions/30/1/1000000", nil, 1)
}

func TestStatisticVendorBasicStatsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.VendorBasicStatsRequest{}
	_, invocationErr := client.Statistic.VendorBasicStats(
		context.TODO(),
		"m",
		1,
		"ytd",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatisticVendorBasicStatsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatisticVendorBasicStatsWithWireMock", "GET", "/Statistic/vendorbasic/ytd/m/1", nil, 1)
}
