// Code generated by Fern. DO NOT EDIT.

package token_storage_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestTokenStorageAddMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.AddMethodRequest{
		Body: &payabli.RequestTokenStorage{
			CustomerData: &payabli.PayorDataRequest{
				CustomerId: payabli.Int64(
					int64(4440),
				),
			},
			EntryPoint: payabli.String(
				"f743aed24a",
			),
			FallbackAuth: payabli.Bool(
				true,
			),
			PaymentMethod: &payabli.RequestTokenStoragePaymentMethod{
				TokenizeCard: &payabli.TokenizeCard{
					Cardcvv: payabli.String(
						"123",
					),
					Cardexp:    "02/25",
					CardHolder: "John Doe",
					Cardnumber: "4111111111111111",
					Cardzip: payabli.String(
						"12345",
					),
					Method: "card",
				},
			},
		},
	}
	_, invocationErr := client.TokenStorage.AddMethod(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTokenStorageAddMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTokenStorageAddMethodWithWireMock", "POST", "/TokenStorage/add", nil, 1)
}

func TestTokenStorageGetMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.GetMethodRequest{
		CardExpirationFormat: payabli.Int(
			1,
		),
		IncludeTemporary: payabli.Bool(
			false,
		),
	}
	_, invocationErr := client.TokenStorage.GetMethod(
		context.TODO(),
		"32-8877drt00045632-678",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTokenStorageGetMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTokenStorageGetMethodWithWireMock", "GET", "/TokenStorage/32-8877drt00045632-678", map[string]string{"cardExpirationFormat": "1", "includeTemporary": "false"}, 1)
}

func TestTokenStorageRemoveMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.TokenStorage.RemoveMethod(
		context.TODO(),
		"32-8877drt00045632-678",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTokenStorageRemoveMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTokenStorageRemoveMethodWithWireMock", "DELETE", "/TokenStorage/32-8877drt00045632-678", nil, 1)
}

func TestTokenStorageUpdateMethodWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.UpdateMethodRequest{
		Body: &payabli.RequestTokenStorage{
			CustomerData: &payabli.PayorDataRequest{
				CustomerId: payabli.Int64(
					int64(4440),
				),
			},
			EntryPoint: payabli.String(
				"f743aed24a",
			),
			FallbackAuth: payabli.Bool(
				true,
			),
			PaymentMethod: &payabli.RequestTokenStoragePaymentMethod{
				TokenizeCard: &payabli.TokenizeCard{
					Cardcvv: payabli.String(
						"123",
					),
					Cardexp:    "02/25",
					CardHolder: "John Doe",
					Cardnumber: "4111111111111111",
					Cardzip: payabli.String(
						"12345",
					),
					Method: "card",
				},
			},
		},
	}
	_, invocationErr := client.TokenStorage.UpdateMethod(
		context.TODO(),
		"32-8877drt00045632-678",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestTokenStorageUpdateMethodWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestTokenStorageUpdateMethodWithWireMock", "PUT", "/TokenStorage/32-8877drt00045632-678", nil, 1)
}
