// Code generated by Fern. DO NOT EDIT.

// The CloudPayment service enables cloud-based payment terminal integration for in-person transaction processing through connected devices. It manages device pairing and authentication, transaction initiation to remote terminals, and transaction status monitoring for point-of-sale operations. The service handles various transaction types including sales, refunds, and tokenization through connected terminals while maintaining cloud communication for remote management. It supports multiple terminal types and manufacturers, manages terminal settings and configurations, and provides real-time transaction status updates. The service enables unified commerce experiences by bridging in-person and online payment channels.
package cloud
