// Code generated by Fern. DO NOT EDIT.

// The Export service provides document and report generation capabilities for various business documents and data sets. It handles invoice PDF generation with customizable templates and branding, check image retrieval for completed payout transactions, and generated report file access for scheduled reports. The service supports multiple export formats and ensures proper document formatting for business use including logos, itemization, and payment details. Exported documents maintain proper audit trails and can be retrieved programmatically for integration with document management systems or accounting software.
package export
