// Code generated by Fern. DO NOT EDIT.

package import__test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestImportImportBillsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.ImportBillsRequest{
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Import.ImportBills(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestImportImportBillsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestImportImportBillsWithWireMock", "POST", "/Import/billsForm/8cfec329267", nil, 1)
}

func TestImportImportCustomerWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.ImportCustomerRequest{
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Import.ImportCustomer(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestImportImportCustomerWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestImportImportCustomerWithWireMock", "POST", "/Import/customersForm/8cfec329267", nil, 1)
}

func TestImportImportVendorWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.ImportVendorRequest{
		File: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Import.ImportVendor(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestImportImportVendorWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestImportImportVendorWithWireMock", "POST", "/Import/vendorsForm/8cfec329267", nil, 1)
}
