// Code generated by Fern. DO NOT EDIT.

package payabli

import (
	json "encoding/json"
)

type NewPageRequest struct {
	IdempotencyKey *IdempotencyKey `json:"-" url:"-"`
	Body           *PayabliPages   `json:"-" url:"-"`
}

func (n *NewPageRequest) UnmarshalJSON(data []byte) error {
	body := new(PayabliPages)
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	n.Body = body
	return nil
}

func (n *NewPageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(n.Body)
}
