// Code generated by Fern. DO NOT EDIT.

package payabli

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/payabli/sdk-go/internal"
	big "math/big"
)

var (
	verifyAccountDetailsRequestFieldRoutingNumber     = big.NewInt(1 << 0)
	verifyAccountDetailsRequestFieldAccountNumber     = big.NewInt(1 << 1)
	verifyAccountDetailsRequestFieldAccountType       = big.NewInt(1 << 2)
	verifyAccountDetailsRequestFieldCountry           = big.NewInt(1 << 3)
	verifyAccountDetailsRequestFieldAccountHolderType = big.NewInt(1 << 4)
	verifyAccountDetailsRequestFieldHolderName        = big.NewInt(1 << 5)
)

type VerifyAccountDetailsRequest struct {
	// The bank routing number to verify.
	RoutingNumber string `json:"routingNumber" url:"-"`
	// The bank account number to verify.
	AccountNumber string `json:"accountNumber" url:"-"`
	// The type of bank account, such as `Checking` or `Savings`.
	AccountType *string `json:"accountType,omitempty" url:"-"`
	// The ISO country code for the bank account, such as `US`.
	Country *string `json:"country,omitempty" url:"-"`
	// The type of account holder. Accepted values are `personal` or `business`. Required when bank authentication is enabled for the paypoint's organization.
	AccountHolderType *string `json:"accountHolderType,omitempty" url:"-"`
	// The name of the bank account holder. For personal accounts, provide the holder's full name (for example, `Jane Doe`); the value is split on the first space into first and last name. For business accounts, provide the legal business name. Required when bank authentication is enabled for the paypoint's organization.
	HolderName *string `json:"holderName,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VerifyAccountDetailsRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetRoutingNumber sets the RoutingNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetRoutingNumber(routingNumber string) {
	v.RoutingNumber = routingNumber
	v.require(verifyAccountDetailsRequestFieldRoutingNumber)
}

// SetAccountNumber sets the AccountNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetAccountNumber(accountNumber string) {
	v.AccountNumber = accountNumber
	v.require(verifyAccountDetailsRequestFieldAccountNumber)
}

// SetAccountType sets the AccountType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetAccountType(accountType *string) {
	v.AccountType = accountType
	v.require(verifyAccountDetailsRequestFieldAccountType)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetCountry(country *string) {
	v.Country = country
	v.require(verifyAccountDetailsRequestFieldCountry)
}

// SetAccountHolderType sets the AccountHolderType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetAccountHolderType(accountHolderType *string) {
	v.AccountHolderType = accountHolderType
	v.require(verifyAccountDetailsRequestFieldAccountHolderType)
}

// SetHolderName sets the HolderName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsRequest) SetHolderName(holderName *string) {
	v.HolderName = holderName
	v.require(verifyAccountDetailsRequestFieldHolderName)
}

func (v *VerifyAccountDetailsRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifyAccountDetailsRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = VerifyAccountDetailsRequest(body)
	return nil
}

func (v *VerifyAccountDetailsRequest) MarshalJSON() ([]byte, error) {
	type embed VerifyAccountDetailsRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Detailed bank account verification results from the verification network.
var (
	bankAccountVerificationDetailsResponseFieldAba                    = big.NewInt(1 << 0)
	bankAccountVerificationDetailsResponseFieldAccountNumber          = big.NewInt(1 << 1)
	bankAccountVerificationDetailsResponseFieldIsValid                = big.NewInt(1 << 2)
	bankAccountVerificationDetailsResponseFieldErrorMessage           = big.NewInt(1 << 3)
	bankAccountVerificationDetailsResponseFieldVerificationResponse   = big.NewInt(1 << 4)
	bankAccountVerificationDetailsResponseFieldResponseCode           = big.NewInt(1 << 5)
	bankAccountVerificationDetailsResponseFieldResponseValue          = big.NewInt(1 << 6)
	bankAccountVerificationDetailsResponseFieldResponseDescription    = big.NewInt(1 << 7)
	bankAccountVerificationDetailsResponseFieldBankName               = big.NewInt(1 << 8)
	bankAccountVerificationDetailsResponseFieldReportedAccountType    = big.NewInt(1 << 9)
	bankAccountVerificationDetailsResponseFieldAccountAddedDate       = big.NewInt(1 << 10)
	bankAccountVerificationDetailsResponseFieldAccountLastUpdatedDate = big.NewInt(1 << 11)
	bankAccountVerificationDetailsResponseFieldAccountClosedDate      = big.NewInt(1 << 12)
)

type BankAccountVerificationDetailsResponse struct {
	// The ABA routing number that was verified.
	Aba *string `json:"aba,omitempty" url:"aba,omitempty"`
	// The account number that was verified.
	AccountNumber *string `json:"accountNumber,omitempty" url:"accountNumber,omitempty"`
	// Whether the bank account passed verification.
	IsValid bool `json:"isValid" url:"isValid"`
	// Error message if the verification request failed.
	ErrorMessage *string `json:"errorMessage,omitempty" url:"errorMessage,omitempty"`
	// Overall verification outcome. Possible values include `Pass`, `Verified`, `Declined`, `NoData`, `Bypassed`, and `Error`.
	VerificationResponse *string `json:"verificationResponse,omitempty" url:"verificationResponse,omitempty"`
	// Response code returned by the verification network.
	ResponseCode *string `json:"responseCode,omitempty" url:"responseCode,omitempty"`
	// Response value associated with the verification outcome.
	ResponseValue *string `json:"responseValue,omitempty" url:"responseValue,omitempty"`
	// Human-readable description of the verification outcome.
	ResponseDescription *string `json:"responseDescription,omitempty" url:"responseDescription,omitempty"`
	// Name of the bank associated with the routing number.
	BankName *string `json:"bankName,omitempty" url:"bankName,omitempty"`
	// Account type as reported by the verification network, such as `Checking` or `Savings`.
	ReportedAccountType *string `json:"reportedAccountType,omitempty" url:"reportedAccountType,omitempty"`
	// Date the account was first seen by the verification network (ISO 8601 format).
	AccountAddedDate *string `json:"accountAddedDate,omitempty" url:"accountAddedDate,omitempty"`
	// Date the account record was last updated in the verification network (ISO 8601 format).
	AccountLastUpdatedDate *string `json:"accountLastUpdatedDate,omitempty" url:"accountLastUpdatedDate,omitempty"`
	// Date the account was closed, if applicable (ISO 8601 format).
	AccountClosedDate *string `json:"accountClosedDate,omitempty" url:"accountClosedDate,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BankAccountVerificationDetailsResponse) GetAba() *string {
	if b == nil {
		return nil
	}
	return b.Aba
}

func (b *BankAccountVerificationDetailsResponse) GetAccountNumber() *string {
	if b == nil {
		return nil
	}
	return b.AccountNumber
}

func (b *BankAccountVerificationDetailsResponse) GetIsValid() bool {
	if b == nil {
		return false
	}
	return b.IsValid
}

func (b *BankAccountVerificationDetailsResponse) GetErrorMessage() *string {
	if b == nil {
		return nil
	}
	return b.ErrorMessage
}

func (b *BankAccountVerificationDetailsResponse) GetVerificationResponse() *string {
	if b == nil {
		return nil
	}
	return b.VerificationResponse
}

func (b *BankAccountVerificationDetailsResponse) GetResponseCode() *string {
	if b == nil {
		return nil
	}
	return b.ResponseCode
}

func (b *BankAccountVerificationDetailsResponse) GetResponseValue() *string {
	if b == nil {
		return nil
	}
	return b.ResponseValue
}

func (b *BankAccountVerificationDetailsResponse) GetResponseDescription() *string {
	if b == nil {
		return nil
	}
	return b.ResponseDescription
}

func (b *BankAccountVerificationDetailsResponse) GetBankName() *string {
	if b == nil {
		return nil
	}
	return b.BankName
}

func (b *BankAccountVerificationDetailsResponse) GetReportedAccountType() *string {
	if b == nil {
		return nil
	}
	return b.ReportedAccountType
}

func (b *BankAccountVerificationDetailsResponse) GetAccountAddedDate() *string {
	if b == nil {
		return nil
	}
	return b.AccountAddedDate
}

func (b *BankAccountVerificationDetailsResponse) GetAccountLastUpdatedDate() *string {
	if b == nil {
		return nil
	}
	return b.AccountLastUpdatedDate
}

func (b *BankAccountVerificationDetailsResponse) GetAccountClosedDate() *string {
	if b == nil {
		return nil
	}
	return b.AccountClosedDate
}

func (b *BankAccountVerificationDetailsResponse) GetExtraProperties() map[string]interface{} {
	if b == nil {
		return nil
	}
	return b.extraProperties
}

func (b *BankAccountVerificationDetailsResponse) require(field *big.Int) {
	if b.explicitFields == nil {
		b.explicitFields = big.NewInt(0)
	}
	b.explicitFields.Or(b.explicitFields, field)
}

// SetAba sets the Aba field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetAba(aba *string) {
	b.Aba = aba
	b.require(bankAccountVerificationDetailsResponseFieldAba)
}

// SetAccountNumber sets the AccountNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetAccountNumber(accountNumber *string) {
	b.AccountNumber = accountNumber
	b.require(bankAccountVerificationDetailsResponseFieldAccountNumber)
}

// SetIsValid sets the IsValid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetIsValid(isValid bool) {
	b.IsValid = isValid
	b.require(bankAccountVerificationDetailsResponseFieldIsValid)
}

// SetErrorMessage sets the ErrorMessage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetErrorMessage(errorMessage *string) {
	b.ErrorMessage = errorMessage
	b.require(bankAccountVerificationDetailsResponseFieldErrorMessage)
}

// SetVerificationResponse sets the VerificationResponse field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetVerificationResponse(verificationResponse *string) {
	b.VerificationResponse = verificationResponse
	b.require(bankAccountVerificationDetailsResponseFieldVerificationResponse)
}

// SetResponseCode sets the ResponseCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetResponseCode(responseCode *string) {
	b.ResponseCode = responseCode
	b.require(bankAccountVerificationDetailsResponseFieldResponseCode)
}

// SetResponseValue sets the ResponseValue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetResponseValue(responseValue *string) {
	b.ResponseValue = responseValue
	b.require(bankAccountVerificationDetailsResponseFieldResponseValue)
}

// SetResponseDescription sets the ResponseDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetResponseDescription(responseDescription *string) {
	b.ResponseDescription = responseDescription
	b.require(bankAccountVerificationDetailsResponseFieldResponseDescription)
}

// SetBankName sets the BankName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetBankName(bankName *string) {
	b.BankName = bankName
	b.require(bankAccountVerificationDetailsResponseFieldBankName)
}

// SetReportedAccountType sets the ReportedAccountType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetReportedAccountType(reportedAccountType *string) {
	b.ReportedAccountType = reportedAccountType
	b.require(bankAccountVerificationDetailsResponseFieldReportedAccountType)
}

// SetAccountAddedDate sets the AccountAddedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetAccountAddedDate(accountAddedDate *string) {
	b.AccountAddedDate = accountAddedDate
	b.require(bankAccountVerificationDetailsResponseFieldAccountAddedDate)
}

// SetAccountLastUpdatedDate sets the AccountLastUpdatedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetAccountLastUpdatedDate(accountLastUpdatedDate *string) {
	b.AccountLastUpdatedDate = accountLastUpdatedDate
	b.require(bankAccountVerificationDetailsResponseFieldAccountLastUpdatedDate)
}

// SetAccountClosedDate sets the AccountClosedDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (b *BankAccountVerificationDetailsResponse) SetAccountClosedDate(accountClosedDate *string) {
	b.AccountClosedDate = accountClosedDate
	b.require(bankAccountVerificationDetailsResponseFieldAccountClosedDate)
}

func (b *BankAccountVerificationDetailsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BankAccountVerificationDetailsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BankAccountVerificationDetailsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BankAccountVerificationDetailsResponse) MarshalJSON() ([]byte, error) {
	type embed BankAccountVerificationDetailsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*b),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, b.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (b *BankAccountVerificationDetailsResponse) String() string {
	if b == nil {
		return "<nil>"
	}
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

// Response wrapper for the bank account verification details endpoint.
var (
	verifyAccountDetailsResponseFieldIsSuccess    = big.NewInt(1 << 0)
	verifyAccountDetailsResponseFieldResponseText = big.NewInt(1 << 1)
	verifyAccountDetailsResponseFieldResponseData = big.NewInt(1 << 2)
)

type VerifyAccountDetailsResponse struct {
	IsSuccess    *IsSuccess                              `json:"isSuccess,omitempty" url:"isSuccess,omitempty"`
	ResponseText ResponseText                            `json:"responseText" url:"responseText"`
	ResponseData *BankAccountVerificationDetailsResponse `json:"responseData,omitempty" url:"responseData,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (v *VerifyAccountDetailsResponse) GetIsSuccess() *IsSuccess {
	if v == nil {
		return nil
	}
	return v.IsSuccess
}

func (v *VerifyAccountDetailsResponse) GetResponseText() ResponseText {
	if v == nil {
		return ""
	}
	return v.ResponseText
}

func (v *VerifyAccountDetailsResponse) GetResponseData() *BankAccountVerificationDetailsResponse {
	if v == nil {
		return nil
	}
	return v.ResponseData
}

func (v *VerifyAccountDetailsResponse) GetExtraProperties() map[string]interface{} {
	if v == nil {
		return nil
	}
	return v.extraProperties
}

func (v *VerifyAccountDetailsResponse) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetIsSuccess sets the IsSuccess field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsResponse) SetIsSuccess(isSuccess *IsSuccess) {
	v.IsSuccess = isSuccess
	v.require(verifyAccountDetailsResponseFieldIsSuccess)
}

// SetResponseText sets the ResponseText field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsResponse) SetResponseText(responseText ResponseText) {
	v.ResponseText = responseText
	v.require(verifyAccountDetailsResponseFieldResponseText)
}

// SetResponseData sets the ResponseData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifyAccountDetailsResponse) SetResponseData(responseData *BankAccountVerificationDetailsResponse) {
	v.ResponseData = responseData
	v.require(verifyAccountDetailsResponseFieldResponseData)
}

func (v *VerifyAccountDetailsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifyAccountDetailsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*v = VerifyAccountDetailsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *v)
	if err != nil {
		return err
	}
	v.extraProperties = extraProperties
	v.rawJSON = json.RawMessage(data)
	return nil
}

func (v *VerifyAccountDetailsResponse) MarshalJSON() ([]byte, error) {
	type embed VerifyAccountDetailsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (v *VerifyAccountDetailsResponse) String() string {
	if v == nil {
		return "<nil>"
	}
	if len(v.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(v.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
