// Code generated by Fern. DO NOT EDIT.

package payabli

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
	time "time"
)

func TestSettersSearchNotificationLogsRequest(t *testing.T) {
	t.Run("SetPageSize", func(t *testing.T) {
		obj := &SearchNotificationLogsRequest{}
		var fernTestValuePageSize *Pagesize
		obj.SetPageSize(fernTestValuePageSize)
		assert.Equal(t, fernTestValuePageSize, obj.PageSize)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPage", func(t *testing.T) {
		obj := &SearchNotificationLogsRequest{}
		var fernTestValuePage *int
		obj.SetPage(fernTestValuePage)
		assert.Equal(t, fernTestValuePage, obj.Page)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSearchNotificationLogsRequest(t *testing.T) {
	t.Run("SetPageSize_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchNotificationLogsRequest{}
		var fernTestValuePageSize *Pagesize

		// Act
		obj.SetPageSize(fernTestValuePageSize)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchNotificationLogsRequest{}
		var fernTestValuePage *int

		// Act
		obj.SetPage(fernTestValuePage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersKeyValueArray(t *testing.T) {
	t.Run("SetKey", func(t *testing.T) {
		obj := &KeyValueArray{}
		var fernTestValueKey *string
		obj.SetKey(fernTestValueKey)
		assert.Equal(t, fernTestValueKey, obj.Key)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValue", func(t *testing.T) {
		obj := &KeyValueArray{}
		var fernTestValueValue []string
		obj.SetValue(fernTestValueValue)
		assert.Equal(t, fernTestValueValue, obj.Value)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersKeyValueArray(t *testing.T) {
	t.Run("GetKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		var expected *string
		obj.Key = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKey(), "getter should return the property value")
	})

	t.Run("GetKey_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		obj.Key = nil

		// Act & Assert
		assert.Nil(t, obj.GetKey(), "getter should return nil when property is nil")
	})

	t.Run("GetKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *KeyValueArray
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKey() // Should return zero value
	})

	t.Run("GetValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		var expected []string
		obj.Value = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValue(), "getter should return the property value")
	})

	t.Run("GetValue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		obj.Value = nil

		// Act & Assert
		assert.Nil(t, obj.GetValue(), "getter should return nil when property is nil")
	})

	t.Run("GetValue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *KeyValueArray
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValue() // Should return zero value
	})

}

func TestSettersMarkExplicitKeyValueArray(t *testing.T) {
	t.Run("SetKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		var fernTestValueKey *string

		// Act
		obj.SetKey(fernTestValueKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}
		var fernTestValueValue []string

		// Act
		obj.SetValue(fernTestValueValue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNotificationLog(t *testing.T) {
	t.Run("SetOrgId", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueOrgId *int64
		obj.SetOrgId(fernTestValueOrgId)
		assert.Equal(t, fernTestValueOrgId, obj.OrgId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaypointId", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValuePaypointId *int64
		obj.SetPaypointId(fernTestValuePaypointId)
		assert.Equal(t, fernTestValuePaypointId, obj.PaypointId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNotificationEvent", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueNotificationEvent *string
		obj.SetNotificationEvent(fernTestValueNotificationEvent)
		assert.Equal(t, fernTestValueNotificationEvent, obj.NotificationEvent)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponseStatus", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueResponseStatus *string
		obj.SetResponseStatus(fernTestValueResponseStatus)
		assert.Equal(t, fernTestValueResponseStatus, obj.ResponseStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetJobData", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueJobData *string
		obj.SetJobData(fernTestValueJobData)
		assert.Equal(t, fernTestValueJobData, obj.JobData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedDate", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueCreatedDate time.Time
		obj.SetCreatedDate(fernTestValueCreatedDate)
		assert.Equal(t, fernTestValueCreatedDate, obj.CreatedDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccessDate", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueSuccessDate *time.Time
		obj.SetSuccessDate(fernTestValueSuccessDate)
		assert.Equal(t, fernTestValueSuccessDate, obj.SuccessDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastFailedDate", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueLastFailedDate *time.Time
		obj.SetLastFailedDate(fernTestValueLastFailedDate)
		assert.Equal(t, fernTestValueLastFailedDate, obj.LastFailedDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsInProgress", func(t *testing.T) {
		obj := &NotificationLog{}
		var fernTestValueIsInProgress bool
		obj.SetIsInProgress(fernTestValueIsInProgress)
		assert.Equal(t, fernTestValueIsInProgress, obj.IsInProgress)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNotificationLog(t *testing.T) {
	t.Run("GetOrgId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *int64
		obj.OrgId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrgId(), "getter should return the property value")
	})

	t.Run("GetOrgId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.OrgId = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrgId(), "getter should return nil when property is nil")
	})

	t.Run("GetOrgId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrgId() // Should return zero value
	})

	t.Run("GetPaypointId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *int64
		obj.PaypointId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPaypointId(), "getter should return the property value")
	})

	t.Run("GetPaypointId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.PaypointId = nil

		// Act & Assert
		assert.Nil(t, obj.GetPaypointId(), "getter should return nil when property is nil")
	})

	t.Run("GetPaypointId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPaypointId() // Should return zero value
	})

	t.Run("GetNotificationEvent", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *string
		obj.NotificationEvent = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNotificationEvent(), "getter should return the property value")
	})

	t.Run("GetNotificationEvent_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.NotificationEvent = nil

		// Act & Assert
		assert.Nil(t, obj.GetNotificationEvent(), "getter should return nil when property is nil")
	})

	t.Run("GetNotificationEvent_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNotificationEvent() // Should return zero value
	})

	t.Run("GetTarget", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *string
		obj.Target = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTarget(), "getter should return the property value")
	})

	t.Run("GetTarget_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.Target = nil

		// Act & Assert
		assert.Nil(t, obj.GetTarget(), "getter should return nil when property is nil")
	})

	t.Run("GetTarget_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTarget() // Should return zero value
	})

	t.Run("GetResponseStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *string
		obj.ResponseStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponseStatus(), "getter should return the property value")
	})

	t.Run("GetResponseStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.ResponseStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponseStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetResponseStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponseStatus() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetJobData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *string
		obj.JobData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetJobData(), "getter should return the property value")
	})

	t.Run("GetJobData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.JobData = nil

		// Act & Assert
		assert.Nil(t, obj.GetJobData(), "getter should return nil when property is nil")
	})

	t.Run("GetJobData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetJobData() // Should return zero value
	})

	t.Run("GetCreatedDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected time.Time
		obj.CreatedDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedDate(), "getter should return the property value")
	})

	t.Run("GetCreatedDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedDate() // Should return zero value
	})

	t.Run("GetSuccessDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *time.Time
		obj.SuccessDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccessDate(), "getter should return the property value")
	})

	t.Run("GetSuccessDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.SuccessDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccessDate(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccessDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccessDate() // Should return zero value
	})

	t.Run("GetLastFailedDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected *time.Time
		obj.LastFailedDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastFailedDate(), "getter should return the property value")
	})

	t.Run("GetLastFailedDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		obj.LastFailedDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastFailedDate(), "getter should return nil when property is nil")
	})

	t.Run("GetLastFailedDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastFailedDate() // Should return zero value
	})

	t.Run("GetIsInProgress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var expected bool
		obj.IsInProgress = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsInProgress(), "getter should return the property value")
	})

	t.Run("GetIsInProgress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsInProgress() // Should return zero value
	})

}

func TestSettersMarkExplicitNotificationLog(t *testing.T) {
	t.Run("SetOrgId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueOrgId *int64

		// Act
		obj.SetOrgId(fernTestValueOrgId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaypointId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValuePaypointId *int64

		// Act
		obj.SetPaypointId(fernTestValuePaypointId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNotificationEvent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueNotificationEvent *string

		// Act
		obj.SetNotificationEvent(fernTestValueNotificationEvent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponseStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueResponseStatus *string

		// Act
		obj.SetResponseStatus(fernTestValueResponseStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetJobData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueJobData *string

		// Act
		obj.SetJobData(fernTestValueJobData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueCreatedDate time.Time

		// Act
		obj.SetCreatedDate(fernTestValueCreatedDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccessDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueSuccessDate *time.Time

		// Act
		obj.SetSuccessDate(fernTestValueSuccessDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastFailedDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueLastFailedDate *time.Time

		// Act
		obj.SetLastFailedDate(fernTestValueLastFailedDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsInProgress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}
		var fernTestValueIsInProgress bool

		// Act
		obj.SetIsInProgress(fernTestValueIsInProgress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNotificationLogDetail(t *testing.T) {
	t.Run("SetOrgId", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueOrgId *int64
		obj.SetOrgId(fernTestValueOrgId)
		assert.Equal(t, fernTestValueOrgId, obj.OrgId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaypointId", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValuePaypointId *int64
		obj.SetPaypointId(fernTestValuePaypointId)
		assert.Equal(t, fernTestValuePaypointId, obj.PaypointId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNotificationEvent", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueNotificationEvent *string
		obj.SetNotificationEvent(fernTestValueNotificationEvent)
		assert.Equal(t, fernTestValueNotificationEvent, obj.NotificationEvent)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTarget", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueTarget *string
		obj.SetTarget(fernTestValueTarget)
		assert.Equal(t, fernTestValueTarget, obj.Target)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponseStatus", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueResponseStatus *string
		obj.SetResponseStatus(fernTestValueResponseStatus)
		assert.Equal(t, fernTestValueResponseStatus, obj.ResponseStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccess", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueSuccess bool
		obj.SetSuccess(fernTestValueSuccess)
		assert.Equal(t, fernTestValueSuccess, obj.Success)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetJobData", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueJobData *string
		obj.SetJobData(fernTestValueJobData)
		assert.Equal(t, fernTestValueJobData, obj.JobData)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCreatedDate", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueCreatedDate time.Time
		obj.SetCreatedDate(fernTestValueCreatedDate)
		assert.Equal(t, fernTestValueCreatedDate, obj.CreatedDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSuccessDate", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueSuccessDate *time.Time
		obj.SetSuccessDate(fernTestValueSuccessDate)
		assert.Equal(t, fernTestValueSuccessDate, obj.SuccessDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLastFailedDate", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueLastFailedDate *time.Time
		obj.SetLastFailedDate(fernTestValueLastFailedDate)
		assert.Equal(t, fernTestValueLastFailedDate, obj.LastFailedDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsInProgress", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueIsInProgress bool
		obj.SetIsInProgress(fernTestValueIsInProgress)
		assert.Equal(t, fernTestValueIsInProgress, obj.IsInProgress)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebHeaders", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueWebHeaders []*StringStringKeyValuePair
		obj.SetWebHeaders(fernTestValueWebHeaders)
		assert.Equal(t, fernTestValueWebHeaders, obj.WebHeaders)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponseHeaders", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueResponseHeaders []*KeyValueArray
		obj.SetResponseHeaders(fernTestValueResponseHeaders)
		assert.Equal(t, fernTestValueResponseHeaders, obj.ResponseHeaders)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetResponseContent", func(t *testing.T) {
		obj := &NotificationLogDetail{}
		var fernTestValueResponseContent *string
		obj.SetResponseContent(fernTestValueResponseContent)
		assert.Equal(t, fernTestValueResponseContent, obj.ResponseContent)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNotificationLogDetail(t *testing.T) {
	t.Run("GetOrgId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *int64
		obj.OrgId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrgId(), "getter should return the property value")
	})

	t.Run("GetOrgId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.OrgId = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrgId(), "getter should return nil when property is nil")
	})

	t.Run("GetOrgId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrgId() // Should return zero value
	})

	t.Run("GetPaypointId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *int64
		obj.PaypointId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPaypointId(), "getter should return the property value")
	})

	t.Run("GetPaypointId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.PaypointId = nil

		// Act & Assert
		assert.Nil(t, obj.GetPaypointId(), "getter should return nil when property is nil")
	})

	t.Run("GetPaypointId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPaypointId() // Should return zero value
	})

	t.Run("GetNotificationEvent", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *string
		obj.NotificationEvent = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNotificationEvent(), "getter should return the property value")
	})

	t.Run("GetNotificationEvent_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.NotificationEvent = nil

		// Act & Assert
		assert.Nil(t, obj.GetNotificationEvent(), "getter should return nil when property is nil")
	})

	t.Run("GetNotificationEvent_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNotificationEvent() // Should return zero value
	})

	t.Run("GetTarget", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *string
		obj.Target = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTarget(), "getter should return the property value")
	})

	t.Run("GetTarget_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.Target = nil

		// Act & Assert
		assert.Nil(t, obj.GetTarget(), "getter should return nil when property is nil")
	})

	t.Run("GetTarget_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTarget() // Should return zero value
	})

	t.Run("GetResponseStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *string
		obj.ResponseStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponseStatus(), "getter should return the property value")
	})

	t.Run("GetResponseStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.ResponseStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponseStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetResponseStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponseStatus() // Should return zero value
	})

	t.Run("GetSuccess", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected bool
		obj.Success = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccess(), "getter should return the property value")
	})

	t.Run("GetSuccess_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccess() // Should return zero value
	})

	t.Run("GetJobData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *string
		obj.JobData = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetJobData(), "getter should return the property value")
	})

	t.Run("GetJobData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.JobData = nil

		// Act & Assert
		assert.Nil(t, obj.GetJobData(), "getter should return nil when property is nil")
	})

	t.Run("GetJobData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetJobData() // Should return zero value
	})

	t.Run("GetCreatedDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected time.Time
		obj.CreatedDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCreatedDate(), "getter should return the property value")
	})

	t.Run("GetCreatedDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCreatedDate() // Should return zero value
	})

	t.Run("GetSuccessDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *time.Time
		obj.SuccessDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSuccessDate(), "getter should return the property value")
	})

	t.Run("GetSuccessDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.SuccessDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetSuccessDate(), "getter should return nil when property is nil")
	})

	t.Run("GetSuccessDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSuccessDate() // Should return zero value
	})

	t.Run("GetLastFailedDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *time.Time
		obj.LastFailedDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLastFailedDate(), "getter should return the property value")
	})

	t.Run("GetLastFailedDate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.LastFailedDate = nil

		// Act & Assert
		assert.Nil(t, obj.GetLastFailedDate(), "getter should return nil when property is nil")
	})

	t.Run("GetLastFailedDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLastFailedDate() // Should return zero value
	})

	t.Run("GetIsInProgress", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected bool
		obj.IsInProgress = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsInProgress(), "getter should return the property value")
	})

	t.Run("GetIsInProgress_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsInProgress() // Should return zero value
	})

	t.Run("GetWebHeaders", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected []*StringStringKeyValuePair
		obj.WebHeaders = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWebHeaders(), "getter should return the property value")
	})

	t.Run("GetWebHeaders_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.WebHeaders = nil

		// Act & Assert
		assert.Nil(t, obj.GetWebHeaders(), "getter should return nil when property is nil")
	})

	t.Run("GetWebHeaders_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWebHeaders() // Should return zero value
	})

	t.Run("GetResponseHeaders", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected []*KeyValueArray
		obj.ResponseHeaders = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponseHeaders(), "getter should return the property value")
	})

	t.Run("GetResponseHeaders_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.ResponseHeaders = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponseHeaders(), "getter should return nil when property is nil")
	})

	t.Run("GetResponseHeaders_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponseHeaders() // Should return zero value
	})

	t.Run("GetResponseContent", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var expected *string
		obj.ResponseContent = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetResponseContent(), "getter should return the property value")
	})

	t.Run("GetResponseContent_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		obj.ResponseContent = nil

		// Act & Assert
		assert.Nil(t, obj.GetResponseContent(), "getter should return nil when property is nil")
	})

	t.Run("GetResponseContent_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetResponseContent() // Should return zero value
	})

}

func TestSettersMarkExplicitNotificationLogDetail(t *testing.T) {
	t.Run("SetOrgId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueOrgId *int64

		// Act
		obj.SetOrgId(fernTestValueOrgId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaypointId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValuePaypointId *int64

		// Act
		obj.SetPaypointId(fernTestValuePaypointId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNotificationEvent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueNotificationEvent *string

		// Act
		obj.SetNotificationEvent(fernTestValueNotificationEvent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTarget_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueTarget *string

		// Act
		obj.SetTarget(fernTestValueTarget)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponseStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueResponseStatus *string

		// Act
		obj.SetResponseStatus(fernTestValueResponseStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccess_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueSuccess bool

		// Act
		obj.SetSuccess(fernTestValueSuccess)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetJobData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueJobData *string

		// Act
		obj.SetJobData(fernTestValueJobData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCreatedDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueCreatedDate time.Time

		// Act
		obj.SetCreatedDate(fernTestValueCreatedDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSuccessDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueSuccessDate *time.Time

		// Act
		obj.SetSuccessDate(fernTestValueSuccessDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLastFailedDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueLastFailedDate *time.Time

		// Act
		obj.SetLastFailedDate(fernTestValueLastFailedDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsInProgress_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueIsInProgress bool

		// Act
		obj.SetIsInProgress(fernTestValueIsInProgress)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebHeaders_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueWebHeaders []*StringStringKeyValuePair

		// Act
		obj.SetWebHeaders(fernTestValueWebHeaders)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponseHeaders_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueResponseHeaders []*KeyValueArray

		// Act
		obj.SetResponseHeaders(fernTestValueResponseHeaders)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetResponseContent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}
		var fernTestValueResponseContent *string

		// Act
		obj.SetResponseContent(fernTestValueResponseContent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersNotificationLogSearchRequest(t *testing.T) {
	t.Run("SetStartDate", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValueStartDate time.Time
		obj.SetStartDate(fernTestValueStartDate)
		assert.Equal(t, fernTestValueStartDate, obj.StartDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetEndDate", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValueEndDate time.Time
		obj.SetEndDate(fernTestValueEndDate)
		assert.Equal(t, fernTestValueEndDate, obj.EndDate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetNotificationEvent", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValueNotificationEvent *string
		obj.SetNotificationEvent(fernTestValueNotificationEvent)
		assert.Equal(t, fernTestValueNotificationEvent, obj.NotificationEvent)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSucceeded", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValueSucceeded *bool
		obj.SetSucceeded(fernTestValueSucceeded)
		assert.Equal(t, fernTestValueSucceeded, obj.Succeeded)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOrgId", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValueOrgId *int64
		obj.SetOrgId(fernTestValueOrgId)
		assert.Equal(t, fernTestValueOrgId, obj.OrgId)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPaypointId", func(t *testing.T) {
		obj := &NotificationLogSearchRequest{}
		var fernTestValuePaypointId *int64
		obj.SetPaypointId(fernTestValuePaypointId)
		assert.Equal(t, fernTestValuePaypointId, obj.PaypointId)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersNotificationLogSearchRequest(t *testing.T) {
	t.Run("GetStartDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected time.Time
		obj.StartDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStartDate(), "getter should return the property value")
	})

	t.Run("GetStartDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStartDate() // Should return zero value
	})

	t.Run("GetEndDate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected time.Time
		obj.EndDate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEndDate(), "getter should return the property value")
	})

	t.Run("GetEndDate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEndDate() // Should return zero value
	})

	t.Run("GetNotificationEvent", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected *string
		obj.NotificationEvent = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetNotificationEvent(), "getter should return the property value")
	})

	t.Run("GetNotificationEvent_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		obj.NotificationEvent = nil

		// Act & Assert
		assert.Nil(t, obj.GetNotificationEvent(), "getter should return nil when property is nil")
	})

	t.Run("GetNotificationEvent_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetNotificationEvent() // Should return zero value
	})

	t.Run("GetSucceeded", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected *bool
		obj.Succeeded = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSucceeded(), "getter should return the property value")
	})

	t.Run("GetSucceeded_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		obj.Succeeded = nil

		// Act & Assert
		assert.Nil(t, obj.GetSucceeded(), "getter should return nil when property is nil")
	})

	t.Run("GetSucceeded_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSucceeded() // Should return zero value
	})

	t.Run("GetOrgId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected *int64
		obj.OrgId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOrgId(), "getter should return the property value")
	})

	t.Run("GetOrgId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		obj.OrgId = nil

		// Act & Assert
		assert.Nil(t, obj.GetOrgId(), "getter should return nil when property is nil")
	})

	t.Run("GetOrgId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOrgId() // Should return zero value
	})

	t.Run("GetPaypointId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var expected *int64
		obj.PaypointId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetPaypointId(), "getter should return the property value")
	})

	t.Run("GetPaypointId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		obj.PaypointId = nil

		// Act & Assert
		assert.Nil(t, obj.GetPaypointId(), "getter should return nil when property is nil")
	})

	t.Run("GetPaypointId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetPaypointId() // Should return zero value
	})

}

func TestSettersMarkExplicitNotificationLogSearchRequest(t *testing.T) {
	t.Run("SetStartDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValueStartDate time.Time

		// Act
		obj.SetStartDate(fernTestValueStartDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetEndDate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValueEndDate time.Time

		// Act
		obj.SetEndDate(fernTestValueEndDate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetNotificationEvent_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValueNotificationEvent *string

		// Act
		obj.SetNotificationEvent(fernTestValueNotificationEvent)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSucceeded_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValueSucceeded *bool

		// Act
		obj.SetSucceeded(fernTestValueSucceeded)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOrgId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValueOrgId *int64

		// Act
		obj.SetOrgId(fernTestValueOrgId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPaypointId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}
		var fernTestValuePaypointId *int64

		// Act
		obj.SetPaypointId(fernTestValuePaypointId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersStringStringKeyValuePair(t *testing.T) {
	t.Run("SetKey", func(t *testing.T) {
		obj := &StringStringKeyValuePair{}
		var fernTestValueKey *string
		obj.SetKey(fernTestValueKey)
		assert.Equal(t, fernTestValueKey, obj.Key)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValue", func(t *testing.T) {
		obj := &StringStringKeyValuePair{}
		var fernTestValueValue *string
		obj.SetValue(fernTestValueValue)
		assert.Equal(t, fernTestValueValue, obj.Value)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersStringStringKeyValuePair(t *testing.T) {
	t.Run("GetKey", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		var expected *string
		obj.Key = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKey(), "getter should return the property value")
	})

	t.Run("GetKey_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		obj.Key = nil

		// Act & Assert
		assert.Nil(t, obj.GetKey(), "getter should return nil when property is nil")
	})

	t.Run("GetKey_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StringStringKeyValuePair
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKey() // Should return zero value
	})

	t.Run("GetValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		var expected *string
		obj.Value = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValue(), "getter should return the property value")
	})

	t.Run("GetValue_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		obj.Value = nil

		// Act & Assert
		assert.Nil(t, obj.GetValue(), "getter should return nil when property is nil")
	})

	t.Run("GetValue_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StringStringKeyValuePair
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValue() // Should return zero value
	})

}

func TestSettersMarkExplicitStringStringKeyValuePair(t *testing.T) {
	t.Run("SetKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		var fernTestValueKey *string

		// Act
		obj.SetKey(fernTestValueKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValue_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}
		var fernTestValueValue *string

		// Act
		obj.SetValue(fernTestValueValue)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingKeyValueArray(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &KeyValueArray{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled KeyValueArray
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj KeyValueArray
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj KeyValueArray
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNotificationLog(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLog{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NotificationLog
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLog
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLog
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNotificationLogDetail(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogDetail{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NotificationLogDetail
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLogDetail
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLogDetail
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingNotificationLogSearchRequest(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &NotificationLogSearchRequest{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled NotificationLogSearchRequest
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLogSearchRequest
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj NotificationLogSearchRequest
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingStringStringKeyValuePair(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &StringStringKeyValuePair{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled StringStringKeyValuePair
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj StringStringKeyValuePair
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj StringStringKeyValuePair
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringKeyValueArray(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &KeyValueArray{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *KeyValueArray
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNotificationLog(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLog{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNotificationLogDetail(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLogDetail{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringNotificationLogSearchRequest(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLogSearchRequest{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringStringStringKeyValuePair(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &StringStringKeyValuePair{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StringStringKeyValuePair
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesKeyValueArray(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &KeyValueArray{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *KeyValueArray
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNotificationLog(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLog{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLog
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNotificationLogDetail(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLogDetail{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogDetail
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesNotificationLogSearchRequest(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &NotificationLogSearchRequest{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *NotificationLogSearchRequest
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesStringStringKeyValuePair(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &StringStringKeyValuePair{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *StringStringKeyValuePair
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
