// Code generated by Fern. DO NOT EDIT.

package ocr

import (
	context "context"
	payabli "github.com/payabli/sdk-go"
	core "github.com/payabli/sdk-go/core"
	internal "github.com/payabli/sdk-go/internal"
	option "github.com/payabli/sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (c *Client) OcrDocumentForm(
	ctx context.Context,
	typeResult payabli.TypeResult,
	request *payabli.FileContentImageOnly,
	opts ...option.RequestOption,
) (*payabli.PayabliApiResponseOcr, error) {
	response, err := c.WithRawResponse.OcrDocumentForm(
		ctx,
		typeResult,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) OcrDocumentJson(
	ctx context.Context,
	typeResult payabli.TypeResult,
	request *payabli.FileContentImageOnly,
	opts ...option.RequestOption,
) (*payabli.PayabliApiResponseOcr, error) {
	response, err := c.WithRawResponse.OcrDocumentJson(
		ctx,
		typeResult,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
