// Code generated by Fern. DO NOT EDIT.

package ocr

import (
	context "context"
	http "net/http"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	baseURL string
	caller  *internal.Caller
	header  http.Header
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		WithRawResponse: NewRawClient(options),
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header: options.ToHeader(),
	}
}

func (c *Client) OcrDocumentForm(
	ctx context.Context,
	typeResult sdk.TypeResult,
	request *sdk.FileContentImageOnly,
	opts ...option.RequestOption,
) (*sdk.PayabliApiResponseOcr, error) {
	response, err := c.WithRawResponse.OcrDocumentForm(
		ctx,
		typeResult,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) OcrDocumentJson(
	ctx context.Context,
	typeResult sdk.TypeResult,
	request *sdk.FileContentImageOnly,
	opts ...option.RequestOption,
) (*sdk.PayabliApiResponseOcr, error) {
	response, err := c.WithRawResponse.OcrDocumentJson(
		ctx,
		typeResult,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
