// Code generated by Fern. DO NOT EDIT.

package wallet

import (
	context "context"
	os "os"

	payabli "github.com/payabli/sdk-go"
	core "github.com/payabli/sdk-go/core"
	internal "github.com/payabli/sdk-go/internal"
	option "github.com/payabli/sdk-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	if options.ClientID == "" {
		options.ClientID = os.Getenv("OAUTH_CLIENT_ID")
	}
	if options.ClientSecret == "" {
		options.ClientSecret = os.Getenv("OAUTH_CLIENT_SECRET")
	}
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Configure and activate Apple Pay for a Payabli organization
//
// Example:
//
//	request := &payabli.ConfigureOrganizationRequestApplePay{
//	    Cascade: payabli.Bool(
//	        true,
//	    ),
//	    IsEnabled: payabli.Bool(
//	        true,
//	    ),
//	    OrgId: payabli.Int64(
//	        int64(123),
//	    ),
//	}
//	client.Wallet.ConfigureApplePayOrganization(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ConfigureApplePayOrganization(
	ctx context.Context,
	request *payabli.ConfigureOrganizationRequestApplePay,
	opts ...option.RequestOption,
) (*payabli.ConfigureApplePayOrganizationApiResponse, error) {
	response, err := c.WithRawResponse.ConfigureApplePayOrganization(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Configure and activate Apple Pay for a Payabli paypoint
//
// Example:
//
//	request := &payabli.ConfigurePaypointRequestApplePay{
//	    Entry: payabli.String(
//	        "8cfec329267",
//	    ),
//	    IsEnabled: payabli.Bool(
//	        true,
//	    ),
//	}
//	client.Wallet.ConfigureApplePayPaypoint(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ConfigureApplePayPaypoint(
	ctx context.Context,
	request *payabli.ConfigurePaypointRequestApplePay,
	opts ...option.RequestOption,
) (*payabli.ConfigureApplePaypointApiResponse, error) {
	response, err := c.WithRawResponse.ConfigureApplePayPaypoint(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Configure and activate Google Pay for a Payabli organization
//
// Example:
//
//	request := &payabli.ConfigureOrganizationRequestGooglePay{
//	    Cascade: payabli.Bool(
//	        true,
//	    ),
//	    IsEnabled: payabli.Bool(
//	        true,
//	    ),
//	    OrgId: payabli.Int64(
//	        int64(123),
//	    ),
//	}
//	client.Wallet.ConfigureGooglePayOrganization(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ConfigureGooglePayOrganization(
	ctx context.Context,
	request *payabli.ConfigureOrganizationRequestGooglePay,
	opts ...option.RequestOption,
) (*payabli.ConfigureApplePayOrganizationApiResponse, error) {
	response, err := c.WithRawResponse.ConfigureGooglePayOrganization(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Configure and activate Google Pay for a Payabli paypoint
//
// Example:
//
//	request := &payabli.ConfigurePaypointRequestGooglePay{
//	    Entry: payabli.String(
//	        "8cfec329267",
//	    ),
//	    IsEnabled: payabli.Bool(
//	        true,
//	    ),
//	}
//	client.Wallet.ConfigureGooglePayPaypoint(
//	    context.TODO(),
//	    request,
//	)
func (c *Client) ConfigureGooglePayPaypoint(
	ctx context.Context,
	request *payabli.ConfigurePaypointRequestGooglePay,
	opts ...option.RequestOption,
) (*payabli.ConfigureGooglePaypointApiResponse, error) {
	response, err := c.WithRawResponse.ConfigureGooglePayPaypoint(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
