// Code generated by Fern. DO NOT EDIT.

// The Query service provides advanced search and reporting capabilities across all transactional and operational data in the platform. It offers flexible query endpoints for transactions, bills, invoices, customers, vendors, boarding applications, vcards, and subscriptions with support for complex filtering using comparison operators, date ranges, text matching, and array operations. The service provides configurable pagination, sorting, and field selection with options to export results in multiple formats including JSON, CSV, Excel, and PDF. Queries can be scoped to specific entrypoints or organizations and support summary statistics alongside detailed record sets.
package query
