// Code generated by Fern. DO NOT EDIT.

package invoice_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestInvoiceAddInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.AddInvoiceRequest{
		Body: &payabli.InvoiceDataRequest{
			CustomerData: &payabli.PayorDataRequest{
				FirstName: payabli.String(
					"Tamara",
				),
				LastName: payabli.String(
					"Bagratoni",
				),
				CustomerNumber: payabli.String(
					"3",
				),
			},
			InvoiceData: &payabli.BillData{
				Items: []*payabli.BillItem{
					&payabli.BillItem{
						ItemProductName: payabli.String(
							"Adventure Consult",
						),
						ItemDescription: payabli.String(
							"Consultation for Georgian tours",
						),
						ItemCost: 100,
						ItemQty: payabli.Int(
							1,
						),
						ItemMode: payabli.Int(
							1,
						),
						ItemTotalAmount: payabli.Float64(
							1,
						),
					},
					&payabli.BillItem{
						ItemProductName: payabli.String(
							"Deposit ",
						),
						ItemDescription: payabli.String(
							"Deposit for trip planning",
						),
						ItemCost: 882.37,
						ItemQty: payabli.Int(
							1,
						),
						ItemTotalAmount: payabli.Float64(
							1,
						),
					},
				},
				InvoiceDate: payabli.Time(
					payabli.MustParseDate(
						"2025-10-19",
					),
				),
				InvoiceType: payabli.Int(
					0,
				),
				InvoiceStatus: payabli.Int(
					1,
				),
				Frequency: payabli.FrequencyOneTime.Ptr(),
				InvoiceAmount: payabli.Float64(
					982.37,
				),
				Discount: payabli.Float64(
					10,
				),
				InvoiceNumber: payabli.String(
					"INV-3",
				),
			},
		},
	}
	_, invocationErr := client.Invoice.AddInvoice(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceAddInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceAddInvoiceWithWireMock", "POST", "/Invoice/8cfec329267", nil, 1)
}

func TestInvoiceDeleteAttachedFromInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Invoice.DeleteAttachedFromInvoice(
		context.TODO(),
		23548884,
		"0_Bill.pdf",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceDeleteAttachedFromInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceDeleteAttachedFromInvoiceWithWireMock", "DELETE", "/Invoice/attachedFileFromInvoice/23548884/0_Bill.pdf", nil, 1)
}

func TestInvoiceDeleteInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Invoice.DeleteInvoice(
		context.TODO(),
		23548884,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceDeleteInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceDeleteInvoiceWithWireMock", "DELETE", "/Invoice/23548884", nil, 1)
}

func TestInvoiceEditInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.EditInvoiceRequest{
		Body: &payabli.InvoiceDataRequest{
			InvoiceData: &payabli.BillData{
				Items: []*payabli.BillItem{
					&payabli.BillItem{
						ItemProductName: payabli.String(
							"Deposit",
						),
						ItemDescription: payabli.String(
							"Deposit for trip planning",
						),
						ItemCost: 882.37,
						ItemQty: payabli.Int(
							1,
						),
					},
				},
				InvoiceDate: payabli.Time(
					payabli.MustParseDate(
						"2025-10-19",
					),
				),
				InvoiceAmount: payabli.Float64(
					982.37,
				),
				InvoiceNumber: payabli.String(
					"INV-6",
				),
			},
		},
	}
	_, invocationErr := client.Invoice.EditInvoice(
		context.TODO(),
		332,
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceEditInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceEditInvoiceWithWireMock", "PUT", "/Invoice/332", nil, 1)
}

func TestInvoiceGetAttachedFileFromInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.GetAttachedFileFromInvoiceRequest{}
	_, invocationErr := client.Invoice.GetAttachedFileFromInvoice(
		context.TODO(),
		1,
		"filename",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceGetAttachedFileFromInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceGetAttachedFileFromInvoiceWithWireMock", "GET", "/Invoice/attachedFileFromInvoice/1/filename", nil, 1)
}

func TestInvoiceGetInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Invoice.GetInvoice(
		context.TODO(),
		23548884,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceGetInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceGetInvoiceWithWireMock", "GET", "/Invoice/23548884", nil, 1)
}

func TestInvoiceGetInvoiceNumberWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Invoice.GetInvoiceNumber(
		context.TODO(),
		"8cfec329267",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceGetInvoiceNumberWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceGetInvoiceNumberWithWireMock", "GET", "/Invoice/getNumber/8cfec329267", nil, 1)
}

func TestInvoiceListInvoicesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.ListInvoicesRequest{
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			0,
		),
		SortBy: payabli.String(
			"desc(field_name)",
		),
	}
	_, invocationErr := client.Invoice.ListInvoices(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceListInvoicesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceListInvoicesWithWireMock", "GET", "/Query/invoices/8cfec329267", map[string]string{"fromRecord": "251", "limitRecord": "0", "sortBy": "desc(field_name)"}, 1)
}

func TestInvoiceListInvoicesOrgWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.ListInvoicesOrgRequest{
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			0,
		),
		SortBy: payabli.String(
			"desc(field_name)",
		),
	}
	_, invocationErr := client.Invoice.ListInvoicesOrg(
		context.TODO(),
		123,
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceListInvoicesOrgWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceListInvoicesOrgWithWireMock", "GET", "/Query/invoices/org/123", map[string]string{"fromRecord": "251", "limitRecord": "0", "sortBy": "desc(field_name)"}, 1)
}

func TestInvoiceSendInvoiceWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.SendInvoiceRequest{
		Attachfile: payabli.Bool(
			true,
		),
		Mail2: payabli.String(
			"tamara@example.com",
		),
	}
	_, invocationErr := client.Invoice.SendInvoice(
		context.TODO(),
		23548884,
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceSendInvoiceWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceSendInvoiceWithWireMock", "GET", "/Invoice/send/23548884", map[string]string{"attachfile": "true", "mail2": "tamara@example.com"}, 1)
}

func TestInvoiceGetInvoicePdfWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Invoice.GetInvoicePdf(
		context.TODO(),
		23548884,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestInvoiceGetInvoicePdfWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestInvoiceGetInvoicePdfWithWireMock", "GET", "/Export/invoicePdf/23548884", nil, 1)
}
