// Code generated by Fern. DO NOT EDIT.

// The Chargeback service manages dispute and chargeback operations for card transactions under review or reversal. It provides detailed chargeback information including reason codes, amounts, and dispute deadlines for merchant response. The service handles chargeback lifecycle tracking from initial notification through resolution, including status updates for representment submissions. It maintains comprehensive chargeback history and documentation, enables dispute response submission with supporting evidence, and provides analytics on chargeback rates and patterns. The service integrates with transaction records to link chargebacks to original payments and track financial impact.
package chargebacks
