// Code generated by Fern. DO NOT EDIT.

// The Templates service manages customizable document and communication templates for invoices, receipts, emails, and boarding forms. It provides template creation, versioning, and management with support for dynamic field insertion, conditional content, and branding elements. Templates can be configured at organization or paypoint levels with inheritance and override capabilities. The service supports multiple template types including HTML email templates, PDF invoice templates, and boarding application layouts with customizable form fields. It enables consistent branding across customer communications while allowing flexibility for different business units or use cases through template variants.
package templates
