// Code generated by Fern. DO NOT EDIT.

// The Customer service provides comprehensive customer relationship management and identity tracking for payment operations. It handles creation, retrieval, updating, and deletion of customer records with flexible identifier configurations to match business requirements. The service manages customer contact information, billing and shipping addresses, and maintains customer status tracking. Customers can be linked to transactions, store multiple payment methods, manage subscriptions, and track consent preferences for communications. The service supports custom fields for additional data storage and integrates with stored payment methods and transaction history.
package customer
