// Code generated by Fern. DO NOT EDIT.

package customer

import (
	context "context"
	payabli "github.com/payabli/sdk-go"
	core "github.com/payabli/sdk-go/core"
	internal "github.com/payabli/sdk-go/internal"
	option "github.com/payabli/sdk-go/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) AddCustomer(
	ctx context.Context,
	entry payabli.Entrypointfield,
	request *payabli.AddCustomerRequest,
	opts ...option.RequestOption,
) (*core.Response[*payabli.PayabliAPIResponseCustomerQuery], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/single/%v",
		entry,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	if request.IdempotencyKey != nil {
		headers.Add("idempotencyKey", *request.IdempotencyKey)
	}
	headers.Add("Content-Type", "application/json")
	var response *payabli.PayabliAPIResponseCustomerQuery
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.PayabliAPIResponseCustomerQuery]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) DeleteCustomer(
	ctx context.Context,
	// Payabli-generated customer ID. Maps to "Customer ID" column in PartnerHub.
	customerID int,
	opts ...option.RequestOption,
) (*core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/%v",
		customerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payabli.PayabliAPIResponse00Responsedatanonobject
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) GetCustomer(
	ctx context.Context,
	// Payabli-generated customer ID. Maps to "Customer ID" column in PartnerHub.
	customerID int,
	opts ...option.RequestOption,
) (*core.Response[*payabli.CustomerQueryRecords], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/%v",
		customerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payabli.CustomerQueryRecords
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.CustomerQueryRecords]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) LinkCustomerTransaction(
	ctx context.Context,
	// Payabli-generated customer ID. Maps to "Customer ID" column in PartnerHub.
	customerID int,
	// ReferenceId for the transaction (PaymentId).
	transID string,
	opts ...option.RequestOption,
) (*core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/link/%v/%v",
		customerID,
		transID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payabli.PayabliAPIResponse00Responsedatanonobject
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) RequestConsent(
	ctx context.Context,
	// Payabli-generated customer ID. Maps to "Customer ID" column in PartnerHub.
	customerID int,
	opts ...option.RequestOption,
) (*core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/%v/consent",
		customerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payabli.PayabliAPIResponse00Responsedatanonobject
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) UpdateCustomer(
	ctx context.Context,
	// Payabli-generated customer ID. Maps to "Customer ID" column in PartnerHub.
	customerID int,
	request *payabli.CustomerData,
	opts ...option.RequestOption,
) (*core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://api-sandbox.payabli.com/api",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/Customer/%v",
		customerID,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *payabli.PayabliAPIResponse00Responsedatanonobject
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         request,
			Response:        &response,
			ErrorDecoder:    internal.NewErrorDecoder(payabli.ErrorCodes),
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*payabli.PayabliAPIResponse00Responsedatanonobject]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
