// Code generated by Fern. DO NOT EDIT.

package export_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	sdkgo "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestExportExportApplicationsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportApplicationsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportApplications(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/boarding/csv/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchDetailsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchDetailsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatchDetails(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batchDetails/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchDetailsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchDetailsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatchDetailsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batchDetails/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchesWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchesRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatches(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batches/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchesOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchesOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatchesOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batches/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchesOutWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchesOutRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatchesOut(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batchesOut/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBatchesOutOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBatchesOutOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBatchesOutOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/batchesOut/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBillsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBillsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBills(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/bills/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportBillsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportBillsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportBillsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/bills/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportChargebacksWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportChargebacksRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportChargebacks(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/chargebacks/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportChargebacksOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportChargebacksOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportChargebacksOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/chargebacks/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportCustomersWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportCustomersRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportCustomers(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/customers/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportCustomersOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportCustomersOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportCustomersOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/customers/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportInvoicesWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportInvoicesRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportInvoices(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/invoices/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportInvoicesOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportInvoicesOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportInvoicesOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/invoices/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportOrganizationsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportOrganizationsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportOrganizations(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/organizations/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportPayoutWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportPayoutRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportPayout(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/payouts/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportPayoutOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportPayoutOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportPayoutOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/payouts/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportPaypointsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportPaypointsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportPaypoints(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/paypoints/csv/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportSettlementsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportSettlementsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportSettlements(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/settlements/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportSettlementsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportSettlementsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportSettlementsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/settlements/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportSubscriptionsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportSubscriptionsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportSubscriptions(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/subscriptions/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportSubscriptionsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportSubscriptionsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportSubscriptionsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/subscriptions/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportTransactionsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportTransactionsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportTransactions(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/transactions/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportTransactionsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportTransactionsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportTransactionsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/transactions/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportTransferDetailsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportTransferDetailsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
		SortBy: payabli.String(
			"desc(field_name)",
		),
	}
	_, invocationErr := client.Export.ExportTransferDetails(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		1000000,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/transferDetails/csv/8cfec329267/1000000", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000", "sortBy": "desc(field_name)"}, 1)
}

func TestExportExportTransfersWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportTransfersRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
		SortBy: payabli.String(
			"desc(field_name)",
		),
	}
	_, invocationErr := client.Export.ExportTransfers(
		context.TODO(),
		"8cfec329267",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/transfers/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000", "sortBy": "desc(field_name)"}, 1)
}

func TestExportExportVendorsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportVendorsRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportVendors(
		context.TODO(),
		"8cfec329267",
		payabli.ExportFormat1Csv.Ptr(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/vendors/csv/8cfec329267", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}

func TestExportExportVendorsOrgWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ExportVendorsOrgRequest{
		ColumnsExport: payabli.String(
			"BatchDate:Batch_Date,PaypointName:Legal_name",
		),
		FromRecord: payabli.Int(
			251,
		),
		LimitRecord: payabli.Int(
			1000,
		),
	}
	_, invocationErr := client.Export.ExportVendorsOrg(
		context.TODO(),
		payabli.ExportFormat1Csv.Ptr(),
		123,
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/Export/vendors/csv/org/123", map[string]string{"columnsExport": "BatchDate:Batch_Date,PaypointName:Legal_name", "fromRecord": "251", "limitRecord": "1000"}, 1)
}
