// Code generated by Fern. DO NOT EDIT.

package payment_method_domain_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPaymentMethodDomainAddPaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.AddPaymentMethodDomainRequest{
		DomainName: payabli.String(
			"checkout.example.com",
		),
		EntityId: payabli.Int64(
			109,
		),
		EntityType: payabli.String(
			"paypoint",
		),
		ApplePay: &payabli.AddPaymentMethodDomainRequestApplePay{
			IsEnabled: payabli.Bool(
				true,
			),
		},
		GooglePay: &payabli.AddPaymentMethodDomainRequestGooglePay{
			IsEnabled: payabli.Bool(
				true,
			),
		},
	}
	_, invocationErr := client.PaymentMethodDomain.AddPaymentMethodDomain(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/PaymentMethodDomain", nil, 1)
}

func TestPaymentMethodDomainCascadePaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PaymentMethodDomain.CascadePaymentMethodDomain(
		context.TODO(),
		"pmd_b8237fa45c964d8a9ef27160cd42b8c5",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/PaymentMethodDomain/pmd_b8237fa45c964d8a9ef27160cd42b8c5/cascade", nil, 1)
}

func TestPaymentMethodDomainDeletePaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PaymentMethodDomain.DeletePaymentMethodDomain(
		context.TODO(),
		"pmd_b8237fa45c964d8a9ef27160cd42b8c5",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "DELETE", "/PaymentMethodDomain/pmd_b8237fa45c964d8a9ef27160cd42b8c5", nil, 1)
}

func TestPaymentMethodDomainGetPaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PaymentMethodDomain.GetPaymentMethodDomain(
		context.TODO(),
		"pmd_b8237fa45c964d8a9ef27160cd42b8c5",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/PaymentMethodDomain/pmd_b8237fa45c964d8a9ef27160cd42b8c5", nil, 1)
}

func TestPaymentMethodDomainListPaymentMethodDomainsWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.ListPaymentMethodDomainsRequest{
		EntityId: payabli.Int64(
			1147,
		),
		EntityType: payabli.String(
			"paypoint",
		),
	}
	_, invocationErr := client.PaymentMethodDomain.ListPaymentMethodDomains(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/PaymentMethodDomain/list", map[string]string{"entityId": "1147", "entityType": "paypoint"}, 1)
}

func TestPaymentMethodDomainUpdatePaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &payabli.UpdatePaymentMethodDomainRequest{
		ApplePay: &payabli.UpdatePaymentMethodDomainRequestWallet{
			IsEnabled: payabli.Bool(
				false,
			),
		},
		GooglePay: &payabli.UpdatePaymentMethodDomainRequestWallet{
			IsEnabled: payabli.Bool(
				false,
			),
		},
	}
	_, invocationErr := client.PaymentMethodDomain.UpdatePaymentMethodDomain(
		context.TODO(),
		"pmd_b8237fa45c964d8a9ef27160cd42b8c5",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/PaymentMethodDomain/pmd_b8237fa45c964d8a9ef27160cd42b8c5", nil, 1)
}

func TestPaymentMethodDomainVerifyPaymentMethodDomainWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.PaymentMethodDomain.VerifyPaymentMethodDomain(
		context.TODO(),
		"pmd_b8237fa45c964d8a9ef27160cd42b8c5",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/PaymentMethodDomain/pmd_b8237fa45c964d8a9ef27160cd42b8c5/verify", nil, 1)
}
