// Code generated by Fern. DO NOT EDIT.

package hosted_payment_pages_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	payabli "github.com/payabli/sdk-go"
	client "github.com/payabli/sdk-go/client"
	option "github.com/payabli/sdk-go/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestHostedPaymentPagesLoadPageWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.HostedPaymentPages.LoadPage(
		context.TODO(),
		"8cfec329267",
		"pay-your-fees-1",
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestHostedPaymentPagesLoadPageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestHostedPaymentPagesLoadPageWithWireMock", "GET", "/Paypoint/load/8cfec329267/pay-your-fees-1", nil, 1)
}

func TestHostedPaymentPagesNewPageWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.NewPageRequest{
		IdempotencyKey: payabli.String(
			"6B29FC40-CA47-1067-B31D-00DD010662DA",
		),
		Body: &payabli.PayabliPages{},
	}
	_, invocationErr := client.HostedPaymentPages.NewPage(
		context.TODO(),
		"8cfec329267",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestHostedPaymentPagesNewPageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestHostedPaymentPagesNewPageWithWireMock", "POST", "/Paypoint/8cfec329267", nil, 1)
}

func TestHostedPaymentPagesSavePageWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &payabli.PayabliPages{}
	_, invocationErr := client.HostedPaymentPages.SavePage(
		context.TODO(),
		"8cfec329267",
		"pay-your-fees-1",
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestHostedPaymentPagesSavePageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestHostedPaymentPagesSavePageWithWireMock", "PUT", "/Paypoint/8cfec329267/pay-your-fees-1", nil, 1)
}
